const Drive=require('../services/driveStore');
const UserSettings=require('./UserSettings');
const now=()=>new Date().toISOString();
function enrich(p,d){if(!p)return null;const t=d.tenants.find(x=>x.id===p.tenant_id);const pr=t&&d.properties.find(x=>x.id===t.property_id);return {...p,tenant_name:t?.name||null,tenant_cnic:t?.cnic||null,property_name:pr?.name||null,custom_charges:Array.isArray(p.custom_charges)?p.custom_charges:[]};}
function derive(p){const charges=[['monthly_rent','rent_enabled'],['electricity','electricity_enabled'],['gas','gas_enabled'],['previous_dues','previous_dues_enabled']].map(([v,e])=>({value:Math.max(0,Number(p[v])||0),enabled:p[e]!==false}));const total=charges.reduce((s,c)=>s+c.value,0);const received=charges.reduce((s,c)=>s+(c.value>0&&c.enabled?c.value:0),0);const unpaid=charges.filter(c=>c.value>0&&!c.enabled).length;return {total,received,status:total===0?'paid':unpaid===0?'paid':received>0?'partial':'unpaid'};}
class Payment{
 static async findAll(userId,filters={}){const d=await Drive.getData();return d.payments.filter(p=>p.user_id===userId&&(!filters.month||Number(p.month)===Number(filters.month))&&(!filters.year||Number(p.year)===Number(filters.year))&&(!filters.tenantId||p.tenant_id===filters.tenantId)).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).map(p=>enrich(p,d));}
 static async findById(id,userId){const d=await Drive.getData();return enrich(d.payments.find(p=>p.id===id&&p.user_id===userId),d);}
 static async create(data,userId){const {id,tenantId,month,year,monthlyRent,electricity,gas,previousDues,totalPayment,amountPaid,customCharges,status,notes,rentEnabled,electricityEnabled,gasEnabled,previousDuesEnabled}=data;if(!tenantId)throw new Error('Tenant ID is required');if(!month||month<1||month>12)throw new Error('Month must be between 1 and 12');if(!year||year<2000||year>2100)throw new Error('Year must be between 2000 and 2100');if(monthlyRent===undefined||Number(monthlyRent)<0)throw new Error('Monthly rent must be a non-negative number');return Drive.mutate(d=>{if(d.payments.some(p=>p.user_id===userId&&p.tenant_id===tenantId&&Number(p.month)===Number(month)&&Number(p.year)===Number(year)))throw new Error('Payment already exists for this tenant for this month/year');const p={id,user_id:userId,tenant_id:tenantId,month:Number(month),year:Number(year),monthly_rent:Number(monthlyRent)||0,electricity:Number(electricity)||0,gas:Number(gas)||0,previous_dues:Number(previousDues)||0,total_payment:0,amount_paid:0,custom_charges:Array.isArray(customCharges)?customCharges:[],status:'unpaid',notes:notes||null,rent_enabled:rentEnabled!==false,electricity_enabled:electricityEnabled!==false,gas_enabled:gasEnabled!==false,previous_dues_enabled:previousDuesEnabled!==false,created_at:now(),updated_at:now()};const x=derive(p);p.total_payment=x.total;p.amount_paid=x.received;p.status=x.status;d.payments.push(p);return enrich(p,d);});}
 static async update(id,data,userId){return Drive.mutate(d=>{const p=d.payments.find(x=>x.id===id&&x.user_id===userId);if(!p)throw new Error('Payment not found');if(!data.tenantId)throw new Error('Tenant ID is required');if(!data.month||data.month<1||data.month>12)throw new Error('Month must be between 1 and 12');if(!data.year||data.year<2000||data.year>2100)throw new Error('Year must be between 2000 and 2100');if(data.monthlyRent===undefined||Number(data.monthlyRent)<0)throw new Error('Monthly rent must be a non-negative number');if(d.payments.some(x=>x.id!==id&&x.user_id===userId&&x.tenant_id===data.tenantId&&Number(x.month)===Number(data.month)&&Number(x.year)===Number(data.year)))throw new Error('Payment already exists for this tenant for this month/year');Object.assign(p,{tenant_id:data.tenantId,month:Number(data.month),year:Number(data.year),monthly_rent:Number(data.monthlyRent)||0,electricity:Number(data.electricity)||0,gas:Number(data.gas)||0,previous_dues:Number(data.previousDues)||0,custom_charges:Array.isArray(data.customCharges)?data.customCharges:[],notes:data.notes||null,rent_enabled:data.rentEnabled!==false,electricity_enabled:data.electricityEnabled!==false,gas_enabled:data.gasEnabled!==false,previous_dues_enabled:data.previousDuesEnabled!==false,updated_at:now()});const x=derive(p);p.total_payment=x.total;p.amount_paid=x.received;p.status=x.status;return enrich(p,d);});}
 static async delete(id,userId){return Drive.mutate(d=>{const p=d.payments.find(x=>x.id===id&&x.user_id===userId);if(!p)throw new Error('Payment not found');d.payments=d.payments.filter(x=>x.id!==id);return p;});}
 static async clearAll(userId){return Drive.mutate(d=>{d.payments=d.payments.filter(x=>x.user_id!==userId);});}
 static async findByTenant(tenantId,userId){const d=await Drive.getData();return d.payments.filter(p=>p.tenant_id===tenantId&&p.user_id===userId).sort((a,b)=>Number(b.year)-Number(a.year)||Number(b.month)-Number(a.month)).map(p=>enrich(p,d));}
 static async getMonthlySummary(year,month,userId){const list=await this.findAll(userId,{year,month});const total=list.reduce((s,p)=>s+Number(p.total_payment)||0,0);const received=list.reduce((s,p)=>s+Number(p.amount_paid)||0,0);return {year,month,totalPayments:total,amountReceived:received,remainingBalance:Math.max(0,total-received),paymentCount:list.length,paidCount:list.filter(p=>p.status==='paid').length,partialCount:list.filter(p=>p.status==='partial').length,unpaidCount:list.filter(p=>p.status==='unpaid').length};}
 static async getDashboardStats(userId){const d=await Drive.getData();const list=d.payments.filter(p=>p.user_id===userId);const tenants=d.tenants.filter(t=>t.user_id===userId);const properties=d.properties.filter(p=>p.user_id===userId);const total=list.reduce((s,p)=>s+Number(p.total_payment)||0,0);const received=list.reduce((s,p)=>s+Number(p.amount_paid)||0,0);return {totalProperties:properties.length,totalTenants:tenants.length,totalPayments:total,amountReceived:received,remainingBalance:Math.max(0,total-received),paidPayments:list.filter(p=>p.status==='paid').length,partialPayments:list.filter(p=>p.status==='partial').length,unpaidPayments:list.filter(p=>p.status==='unpaid').length};}
 static async ensureCurrentMonthPayments(userId){const nowDate=new Date();const month=nowDate.getMonth()+1,year=nowDate.getFullYear();const tenants=(await require('./Tenant').findAll(userId)).filter(t=>t.status==='active');for(const t of tenants){const existing=await this.findAll(userId,{tenantId:t.id,month,year});if(!existing.length){const p={id:`${t.id}-${year}-${month}`,tenantId:t.id,month,year,monthlyRent:0,electricity:0,gas:0,previousDues:0,rentEnabled:true,electricityEnabled:true,gasEnabled:true,previousDuesEnabled:true};await this.create(p,userId);}}}
}
module.exports=Payment;
