const Drive = require('../services/driveStore');
const RecycleBin = require('./RecycleBin');
const now=()=>new Date().toISOString();
function prop(data, userId){return {id:data.id,user_id:userId,name:data.name,address:data.address,total_rooms:Number(data.totalRooms),base_rent:Number(data.baseRent)||0,status:data.status||'active',description:data.description||null,created_at:data.created_at||now(),updated_at:now()};}
function enrich(p,d){if(!p)return null;const rooms=d.rooms.filter(r=>r.property_id===p.id);const tenants=d.tenants.filter(t=>t.property_id===p.id&&t.status==='active');return {...p,tenant_count:tenants.length,occupied_rooms:rooms.filter(r=>r.status==='occupied').length,total_rooms:rooms.length||p.total_rooms};}
class Property{
 static async findAll(userId){const d=await Drive.getData();return d.properties.filter(p=>p.user_id===userId).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).map(p=>enrich(p,d));}
 static async findById(id,userId){const d=await Drive.getData();const p=d.properties.find(x=>x.id===id&&(!userId||x.user_id===userId));return enrich(p,d);}
 static async create(data,userId){if(!data.name||!data.address||!data.totalRooms||data.totalRooms<1)throw new Error('Name, address, and totalRooms (minimum 1) are required');if(data.baseRent===undefined||data.baseRent<0)throw new Error('Base rent must be a positive number');return Drive.mutate(d=>{const p=prop(data,userId);d.properties.push(p);for(let i=1;i<=p.total_rooms;i++)d.rooms.push({id:`${p.id}-room-${i}`,property_id:p.id,room_number:i,room_name:`Room ${i}`,status:'available',tenant_id:null,rent_amount:p.base_rent});return enrich(p,d);});}
 static async update(id,data,userId){if(!data.name||!data.address||!data.totalRooms||data.totalRooms<1)throw new Error('Name, address, and totalRooms (minimum 1) are required');if(data.baseRent===undefined||data.baseRent<0)throw new Error('Base rent must be a positive number');return Drive.mutate(d=>{const p=d.properties.find(x=>x.id===id&&x.user_id===userId);if(!p)throw new Error('Property not found');const old=Number(p.total_rooms);const next=Number(data.totalRooms);for(let i=next+1;i<=old;i++){const r=d.rooms.find(x=>x.property_id===id&&x.room_number===i);if(r&&r.status==='occupied')throw new Error(`Cannot remove Room ${i} because it is occupied`);}d.rooms=d.rooms.filter(r=>!(r.property_id===id&&r.room_number>next));for(let i=old+1;i<=next;i++)d.rooms.push({id:`${id}-room-${i}`,property_id:id,room_number:i,room_name:`Room ${i}`,status:'available',tenant_id:null,rent_amount:Number(data.baseRent)});Object.assign(p,prop({...data,id},userId),{created_at:p.created_at});return enrich(p,d);});}
 static async delete(id,userId){return Drive.mutate(d=>{const p=d.properties.find(x=>x.id===id&&x.user_id===userId);if(!p)throw new Error('Property not found');const active=d.tenants.filter(t=>t.property_id===id&&t.status==='active');if(active.length)throw new Error(`Cannot delete property with ${active.length} active tenants`);const rooms=d.rooms.filter(r=>r.property_id===id);d.recycleBin.push({id:`rb-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,user_id:userId,type:'property',original_id:id,data:{...p,rooms},deleted_at:now()});d.properties=d.properties.filter(x=>x.id!==id);d.rooms=d.rooms.filter(x=>x.property_id!==id);return p;});}
 static async getRooms(propertyId){const d=await Drive.getData();return d.rooms.filter(r=>r.property_id===propertyId).sort((a,b)=>a.room_number-b.room_number);}
 static async updateRoom(propertyId,roomNumber,data){return Drive.mutate(d=>{const r=d.rooms.find(x=>x.property_id===propertyId&&Number(x.room_number)===Number(roomNumber));if(!r)throw new Error('Room not found');if(data.status&&!['available','occupied','maintenance'].includes(data.status))throw new Error('Invalid status. Must be: available, occupied, or maintenance');if(data.status!==undefined)r.status=data.status;if(data.tenantId!==undefined)r.tenant_id=data.tenantId||null;if(data.rentAmount!==undefined)r.rent_amount=data.rentAmount;if(data.roomName!==undefined)r.room_name=data.roomName||r.room_name;return {...r};});}
 static async addRoom(propertyId,roomNumber,roomName=null,rentAmount=null){return Drive.mutate(d=>{if(d.rooms.some(r=>r.property_id===propertyId&&Number(r.room_number)===Number(roomNumber)))throw new Error('Room number already exists');const p=d.properties.find(x=>x.id===propertyId);const r={id:`${propertyId}-room-${roomNumber}`,property_id:propertyId,room_number:Number(roomNumber),room_name:roomName||`Room ${roomNumber}`,status:'available',tenant_id:null,rent_amount:rentAmount??p?.base_rent??0};d.rooms.push(r);if(p&&Number(roomNumber)>p.total_rooms)p.total_rooms=Number(roomNumber);return r;});}
 static async removeRoom(propertyId,roomNumber){return Drive.mutate(d=>{const i=d.rooms.findIndex(r=>r.property_id===propertyId&&Number(r.room_number)===Number(roomNumber));if(i<0)throw new Error('Room not found');if(d.rooms[i].status==='occupied')throw new Error(`Cannot remove Room ${roomNumber} because it is occupied`);const [r]=d.rooms.splice(i,1);return r;});}
}
module.exports=Property;
