const Drive=require('../services/driveStore');
const now=()=>new Date().toISOString();
class RecycleBin{
 static async addTenant(tenantData,userId){return Drive.mutate(d=>{const item={id:`rb-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,user_id:userId,type:'tenant',original_id:tenantData.id,data:JSON.parse(JSON.stringify(tenantData)),deleted_at:now()};d.recycleBin.push(item);return item;});}
 static async addProperty(propertyData,userId,rooms=[]){return Drive.mutate(d=>{const item={id:`rb-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,user_id:userId,type:'property',original_id:propertyData.id,data:{...JSON.parse(JSON.stringify(propertyData)),rooms:JSON.parse(JSON.stringify(rooms))},deleted_at:now()};d.recycleBin.push(item);return item;});}
 static async getAll(userId,type=null){const d=await Drive.getData();return d.recycleBin.filter(x=>x.user_id===userId&&(!type||x.type===type)).sort((a,b)=>String(b.deleted_at).localeCompare(String(a.deleted_at)));}
 static async getById(id,userId){const d=await Drive.getData();return d.recycleBin.find(x=>x.id===id&&x.user_id===userId)||null;}
 static async recover(id,userId){return Drive.mutate(d=>{const item=d.recycleBin.find(x=>x.id===id&&x.user_id===userId);if(!item)throw new Error('Recycle bin item not found');const warnings=[];if(item.type==='tenant'){const archivedPayments=Array.isArray(item.data.archivedPayments)?item.data.archivedPayments:[];const t={...item.data,id:item.original_id,user_id:userId,documents:Array.isArray(item.data.documents)?item.data.documents:[]};delete t.archivedPayments;if(d.tenants.some(x=>x.id===t.id))throw new Error('A tenant with this ID already exists');if(t.cnic&&d.tenants.some(x=>x.user_id===userId&&x.cnic===t.cnic))throw new Error('A tenant with this CNIC already exists');if(t.property_id&&t.room_number){const r=d.rooms.find(x=>x.property_id===t.property_id&&Number(x.room_number)===Number(t.room_number));if(r&&r.status==='occupied'&&r.tenant_id!==t.id){warnings.push('The original room is occupied, so the tenant was recovered without a room assignment.');t.property_id=null;t.room_number=null;}else if(r){r.status='occupied';r.tenant_id=t.id;}}d.tenants.push(t);const existingPaymentIds=new Set(d.payments.map(p=>p.id));for(const payment of archivedPayments){if(!existingPaymentIds.has(payment.id))d.payments.push({...payment,tenant_id:t.id,user_id:userId});}}else if(item.type==='property'){const p={...item.data,id:item.original_id,user_id:userId};if(d.properties.some(x=>x.id===p.id))throw new Error('A property with this ID already exists');const rooms=Array.isArray(p.rooms)?p.rooms:[];delete p.rooms;d.properties.push(p);for(const r of rooms)d.rooms.push({...r,id:r.id||`${p.id}-room-${r.room_number}`,property_id:p.id});if(!rooms.length&&p.total_rooms){for(let i=1;i<=p.total_rooms;i++)d.rooms.push({id:`${p.id}-room-${i}`,property_id:p.id,room_number:i,room_name:`Room ${i}`,status:'available',tenant_id:null,rent_amount:p.base_rent});warnings.push('Rooms were recreated as available.');}}d.recycleBin=d.recycleBin.filter(x=>x.id!==id);return {item,warnings};});}
 static async deletePermanently(id,userId){return Drive.mutate(d=>{const item=d.recycleBin.find(x=>x.id===id&&x.user_id===userId);if(!item)throw new Error('Recycle bin item not found');d.recycleBin=d.recycleBin.filter(x=>x.id!==id);return item;});}
 static async clearAll(userId){return Drive.mutate(d=>{d.recycleBin=d.recycleBin.filter(x=>x.user_id!==userId);});}
 static async clearAllByType(type,userId){return Drive.mutate(d=>{d.recycleBin=d.recycleBin.filter(x=>!(x.user_id===userId&&x.type===type));});}
 static async deleteOldItems(userId,days=15){return Drive.mutate(d=>{const cutoff=Date.now()-days*86400000;d.recycleBin=d.recycleBin.filter(x=>!(x.user_id===userId&&new Date(x.deleted_at).getTime()<cutoff));});}
 static async getCount(userId){return (await this.getAll(userId)).length;}
 static async getCountByType(type,userId){return (await this.getAll(userId,type)).length;}
}
module.exports=RecycleBin;
