const Drive=require('../services/driveStore');
const Property=require('./Property');
const now=()=>new Date().toISOString();
function enrich(t,d){if(!t)return null;const p=d.properties.find(x=>x.id===t.property_id);return {...t,property_name:p?.name||null,property_address:p?.address||null,documents:Array.isArray(t.documents)?t.documents:[]};}
class Tenant{
 static async findAll(userId){const d=await Drive.getData();return d.tenants.filter(t=>t.user_id===userId).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).map(t=>enrich(t,d));}
 static async findById(id,userId){const d=await Drive.getData();return enrich(d.tenants.find(t=>t.id===id&&t.user_id===userId),d);}
 static async create(data,userId){const {id,name,fatherName,cnic,location,description,propertyId,roomNumber,status,profile_pic,documents,mobileNumber,advancePayment,leaseEndDate}=data;if(!name||!fatherName||!cnic||!location)throw new Error('Required fields missing: name, fatherName, cnic, location');return Drive.mutate(d=>{if(d.tenants.some(t=>t.user_id===userId&&t.cnic===cnic))throw new Error('A tenant with this CNIC already exists');const t={id,user_id:userId,name,father_name:fatherName,cnic,location,description:description||null,property_id:propertyId||null,room_number:roomNumber||null,status:status||'active',profile_pic:profile_pic||null,documents:Array.isArray(documents)?documents:[],mobile_number:mobileNumber||null,advance_payment:Number(advancePayment)||0,lease_end_date:leaseEndDate||null,created_at:now(),updated_at:now()};d.tenants.push(t);if(t.property_id&&t.room_number){const r=d.rooms.find(x=>x.property_id===t.property_id&&Number(x.room_number)===Number(t.room_number));if(r){r.status='occupied';r.tenant_id=t.id;}}return enrich(t,d);});}
 static async update(id,data,userId){const {name,fatherName,cnic,location,description,propertyId,roomNumber,status,profile_pic,documents,mobileNumber,advancePayment,leaseEndDate}=data;if(!name||!fatherName||!cnic||!location)throw new Error('Required fields missing: name, fatherName, cnic, location');return Drive.mutate(d=>{const t=d.tenants.find(x=>x.id===id&&x.user_id===userId);if(!t)throw new Error('Tenant not found');if(d.tenants.some(x=>x.user_id===userId&&x.id!==id&&x.cnic===cnic))throw new Error('A tenant with this CNIC already exists');if(t.property_id&&t.room_number){const old=d.rooms.find(r=>r.property_id===t.property_id&&Number(r.room_number)===Number(t.room_number));if(old&&old.tenant_id===id){old.status='available';old.tenant_id=null;}}Object.assign(t,{name,father_name:fatherName,cnic,location,description:description||null,property_id:propertyId||null,room_number:roomNumber||null,status:status||'active',profile_pic:profile_pic!==undefined?profile_pic:null,documents:Array.isArray(documents)?documents:[],mobile_number:mobileNumber!==undefined?(mobileNumber||null):t.mobile_number,advance_payment:advancePayment!==undefined?(Number(advancePayment)||0):t.advance_payment,lease_end_date:leaseEndDate!==undefined?(leaseEndDate||null):t.lease_end_date,updated_at:now()});if(t.property_id&&t.room_number){const r=d.rooms.find(x=>x.property_id===t.property_id&&Number(x.room_number)===Number(t.room_number));if(r){r.status='occupied';r.tenant_id=id;}}return enrich(t,d);});}
 static async delete(id,userId){return Drive.mutate(d=>{const t=d.tenants.find(x=>x.id===id&&x.user_id===userId);if(!t)throw new Error('Tenant not found');if(t.property_id&&t.room_number){const r=d.rooms.find(x=>x.property_id===t.property_id&&Number(x.room_number)===Number(t.room_number));if(r&&r.tenant_id===id){r.status='available';r.tenant_id=null;}}const archivedPayments=d.payments.filter(p=>p.tenant_id===id&&(!p.user_id||p.user_id===userId)).map(p=>JSON.parse(JSON.stringify(p)));const archivedTenant={...JSON.parse(JSON.stringify(t)),archivedPayments};d.recycleBin.push({id:`rb-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,user_id:userId,type:'tenant',original_id:id,data:archivedTenant,deleted_at:now()});d.tenants=d.tenants.filter(x=>x.id!==id);d.payments=d.payments.filter(p=>!(p.tenant_id===id&&(!p.user_id||p.user_id===userId)));return t;});}
 static async findByProperty(propertyId,userId){const d=await Drive.getData();return d.tenants.filter(t=>t.property_id===propertyId&&t.user_id===userId).sort((a,b)=>(a.room_number||0)-(b.room_number||0)).map(t=>enrich(t,d));}
 static async clearAll(userId){return Drive.mutate(d=>{const ids=new Set(d.tenants.filter(t=>t.user_id===userId).map(t=>t.id));d.tenants=d.tenants.filter(t=>t.user_id!==userId);d.payments=d.payments.filter(p=>!ids.has(p.tenant_id));});}
 static async findByCNIC(cnic,userId){const d=await Drive.getData();return enrich(d.tenants.find(t=>t.cnic===cnic&&t.user_id===userId),d);}
 static async findWithPayments(id,userId){const t=await this.findById(id,userId);if(!t)return null;const d=await Drive.getData();t.payments=d.payments.filter(p=>p.tenant_id===id).sort((a,b)=>String(b.year).localeCompare(String(a.year))||String(b.month).localeCompare(String(a.month)));return t;}
 static async getCountByStatus(userId){const d=await Drive.getData();const m={};for(const t of d.tenants.filter(x=>x.user_id===userId))m[t.status]=(m[t.status]||0)+1;return Object.entries(m).map(([status,count])=>({status,count}));}
}
module.exports=Tenant;
